### ISSUE TITLE
韩漫库、漫画人、HO5HO已失效，望大佬修复

### ISSUE THREAD

**Issue by LuoChaoIOS** [suiyuran/aidoku-zh-sources#11]
韩漫库、漫画人、HO5HO已失效，望大佬修复

**Comment by Bianzzn** [comment]
作者大人不更新了吗 @suiyuran

**Comment by suiyuran** [comment]
韩漫库我这边测试没有问题，漫画人等着 aidoku-community-sources 修复吧，HO5HO已修复。

**Comment by LuoChaoIOS** [comment]
好的，非常感谢大佬制作的中文源

**Comment by suiyuran** [comment]
> 韩漫库、漫画人、HO5HO已失效，望大佬修复

漫画人已修复。
