### ISSUE TITLE
G站漫画无法加载章节

### ISSUE THREAD

**Issue by Bianzzn** [suiyuran/aidoku-zh-sources#14]
g站漫画可以搜索，但是无法加载出章节 大佬修复下

**Comment by suiyuran** [comment]
已修复

**Comment by Bianzzn** [comment]
谢谢大佬 这个源老出问题

**Comment by suiyuran** [comment]
> 怎么G站漫画的章节列表排序也出问题了😂

已修复

**Comment by QJKuan** [comment]
大佬 我没用过rust 不过这个章节排序逻辑可以用url那个 _xxx （下划线后的数字）来排序吗，我看更新好像是把直接之前的倒序改成正序👀

**Comment by suiyuran** [comment]
> 大佬 我没用过rust 不过这个章节排序逻辑可以用url那个 _xxx （下划线后的数字）来排序吗，我看更新好像是把直接之前的倒序改成正序👀

有些网站是可以通过url上的参数来指定排序的，但G站不行。G站的代码改动太频繁，昨天都还是倒序，今天又改成了顺序。
