### ISSUE TITLE
老哥可以考虑做一下这个网站吗

### ISSUE THREAD

**Issue by 1917431753** [suiyuran/aidoku-zh-sources#16]
https://bakamh.com/    是看韩漫的，他的画质应该是目前最好的，比漫小肆的画质还好一点点，当然也有部分老漫不太好，更新速度有更快也有慢的，当然，主要是他的画质，我总觉得他看着更舒服，哈哈

**Comment by 1917431753** [comment]
较新出的韩漫 画质好一点，其他的倒是差不多

**Comment by suiyuran** [comment]
已添加

**Comment by 1917431753** [comment]
> 已添加

感谢
