### ISSUE TITLE
请问大佬可以考虑添加一下这个源吗，质量非常不错

### ISSUE THREAD

**Issue by YUANCHUANYING** [suiyuran/aidoku-zh-sources#17]
https://noy1.top/  基本上是日漫，漫画质量很好，r18漫画，不过就是需要账号，如果大佬考虑做的话我私您账号

**Comment by suiyuran** [comment]
已添加。需要在浏览器的开发者工具中获取 Cookie，将 NOY_SESSION= 后面部分填入 NoyAcg 图源的会话设置中。
![从 home 请求中查看 Cookie](https://github.com/suiyuran/aidoku-zh-sources/assets/13815102/e0a2d04c-240e-4248-9fa3-1de23871e8f8)

**Comment by YUANCHUANYING** [comment]
> 已添加。需要在浏览器的开发者工具中获取 Cookie，将 NOY_SESSION= 后面部分填入 NoyAcg 图源的会话设置中。 ![从 home 请求中查看 Cookie](https://private-user-images.githubusercontent.com/13815102/291458820-e0a2d04c-240e-4248-9fa3-1de23871e8f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODQwNjUsIm5iZiI6MTcwMjk4Mzc2NSwicGF0aCI6Ii8xMzgxNTEwMi8yOTE0NTg4MjAtZTBhMmQwNGMtMjQwZS00MjQ4LTlmYTMtMWRlMjM4NzFlOGY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDExMDI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiN2Q0YTc5YjBiM2FhMjk4ODZlYTA3Y2NiMDdiMGRiNjExYzhiNzU4YzFjNTFkYWI1YzI5OTk3N2YzNWJjMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lzBWD4hKrkWuPvkiTeJ73FTNLdPRKJlz458HVnQJFhU)

感谢
