### ISSUE TITLE
拷贝漫画搜索api不返回搜索结果列表了

### ISSUE THREAD

**Issue by lpy1997c** [suiyuran/aidoku-zh-sources#20]
拷贝漫画搜索api不返回搜索结果列表了，导致目前APP内拷贝漫画搜索不返回结果，这个可以处理吗
![20240111180126](https://github.com/suiyuran/aidoku-zh-sources/assets/120087040/8a46610d-013f-4674-98b8-ec2a40140721)

**Comment by suiyuran** [comment]
已修复。

**Comment by lpy1997c** [comment]
测试没问题了，感谢
