### ISSUE TITLE
拷贝漫画大陆站源

### ISSUE THREAD

**Issue by mujinhexi998** [suiyuran/aidoku-zh-sources#26]
https://www.mangacopy.com/
大佬能把这个加进去吗

**Comment by suiyuran** [comment]
有拷贝漫画源

**Comment by mujinhexi998** [comment]
那个每次都要魔法才能看> 有拷贝漫画源

**Comment by suiyuran** [comment]
我这边测试直连也是可以的。最近拷贝漫画源有更新，你可以卸载重装试试。

**Comment by SebastianZzzz** [comment]
大佬，我这边测试的话拷贝漫画是不能直连的……可以请您添加mangacopy.com进源吗，谢谢！

**Comment by SebastianZzzz** [comment]
又测试了一次，似乎拷贝漫画的加载比较随缘
