### ISSUE TITLE
大佬看漫画加载问题

### ISSUE THREAD

**Issue by lingran10** [suiyuran/aidoku-zh-sources#31]
我用aidoku看漫画有时会出现，一直加载状态换网络也不行，得等一会在进软件，才能加载出来。
我用aidoku的内置网站选项进入，是可以正常加载并且无缝衔接的。
网络和网址握手两个我都排除了，包括抓包软件加载，网址是一致的。
不清楚是什么问题望解答

**Comment by lingran10** [comment]
是G站漫画的源站

**Comment by tingv** [comment]
+1

**Comment by MckinleyVan** [comment]
> 是G站漫画的源站

我也是，特别是G站漫画，加载速度特别慢，挂不挂代理基本上都是卡住的状态。用网站看很流畅。
个人感觉这个站点的漫画质量最高，大佬可不可以修复一下呀

**Comment by tingv** [comment]
我这好几个源都有这种情况，浏览器开源网站加载挺快的，奇怪
