### ISSUE TITLE
怎么最近有几个站点加载速度很慢怎么回事

### ISSUE THREAD

**Issue by mujinhexi998** [suiyuran/aidoku-zh-sources#33]

**Comment by MckinleyVan** [comment]
我也是，特别是G站漫画，加载速度特别慢，挂不挂代理基本上都是卡住的状态。用网站看很流畅。
个人感觉这个站点的漫画质量最高，大佬可不可以修复一下呀

**Comment by tingv** [comment]
我这好几个源都有这种情况，浏览器开源网站加载挺快的，奇怪
