### ISSUE TITLE
Zero搬运网看到第六话就看不了了，源网站第六话之后要登陆账号

### ISSUE THREAD

**Issue by qoo009** [suiyuran/aidoku-zh-sources#43]

**Comment by suiyuran** [comment]
我没有账号，所以没有实现登录功能。

**Comment by qoo009** [comment]
> 我没有账号，所以没有实现登录功能。

感谢大大，请问一下aidoku 能自己实现登录功能吗

**Comment by suiyuran** [comment]
Aidoku 源可以实现登录功能，比如哔咔漫画。只是因为我没有zero搬运网的 VIP 账号，所以才没有实现登录功能。

**Comment by ASIjacket** [comment]
我稍微改了下，适配了登陆，已经提交了

#44

**Comment by suiyuran** [comment]
已合并。

**Comment by qoo009** [comment]
感谢🙏，刚试了一下，点开之前网站能看，但是Aidoku里还是加载不了，要重新加载源？已经更新v2了

**Comment by ASIjacket** [comment]
> 感谢🙏，刚试了一下，点开之前网站能看，但是Aidoku里还是加载不了，要重新加载源？已经更新v2了

1. 网页登陆以后，点开一个漫画后，打开浏览器开发者工具，点开最新一话，在开发工具 Application 里找到 cookie，找到Ckng_2132_auth 和 Ckng_2132_saltkey 的值
2. 拼接成 `Ckng_2132_saltkey=？？？？; Ckng_2132_auth=？？？;` 
3. 在zero源页面右上三个点里，粘贴
4. 卸载zero源，aiduku设置里清网络缓存，安装源
