### ISSUE TITLE
大佬noyacg可以加入登录配置吗

### ISSUE THREAD

**Issue by suiyuran** [suiyuran/aidoku-zh-sources#47]
大佬noyacg可以加入登录配置吗

_Originally posted by @zhaianan in https://github.com/suiyuran/aidoku-zh-sources/issues/5#issuecomment-2024185509_

**Comment by suiyuran** [comment]
NoyAcg 的登录接口没有将 session 放在 body 里面，而是以 cookie 的形式放在 header 里面。所以我没法做到像哔咔漫画那样，配置用户名和密码，能自动登录。

**Comment by suiyuran** [comment]
session 的配置可以参考这个 issue。 #17

**Comment by zhaianan** [comment]
好的🆗
