### ISSUE TITLE
大佬，链接打不开，添加不了图源

### ISSUE THREAD

**Issue by ZHONG-ZHILIU** [suiyuran/aidoku-zh-sources#5]
怎么添加图源啊？打不开

**Comment by suiyuran** [comment]
设置 > 图源列表 > + > 输入链接 https://raw.githubusercontent.com/suiyuran/aidoku-zh-sources/main/public ，如果不能直接访问，可以使用CDN，比如jsDelivr: https://cdn.jsdelivr.net/gh/suiyuran/aidoku-zh-sources@main/public

**Comment by ZHONG-ZHILIU** [comment]
> 设置 > 图源列表 > + > 输入链接 https://raw.githubusercontent.com/suiyuran/aidoku-zh-sources/main/public ，如果不能直接访问，可以使用CDN，比如jsDelivr: https://cdn.jsdelivr.net/gh/suiyuran/aidoku-zh-sources@main/public

非常感谢大佬的指导！

**Comment by lineagelin** [comment]
使用这两个链接都无法打开：
raw：404: Not Found
jsDelivr：Couldn't find the requested file /public in suiyuran/aidoku-zh-sources.
有什么办法打开吗？

**Comment by suiyuran** [comment]
> 使用这两个链接都无法打开： raw：404: Not Found jsDelivr：Couldn't find the requested file /public in suiyuran/aidoku-zh-sources. 有什么办法打开吗？

没让你直接打开链接，你只需要把链接添加到Aidoku的图源列表里就好了。最新版的图源列表是设置里的来源列表。

**Comment by lineagelin** [comment]
> > 使用这两个链接都无法打开： raw：404: Not Found jsDelivr：Couldn't find the requested file /public in suiyuran/aidoku-zh-sources. 有什么办法打开吗？
> 
> 没让你直接打开链接，你只需要把链接添加到Aidoku的图源列表里就好了。最新版的图源列表是设置里的来源列表。

感谢，已经导入成功。一开始尝试直接导入但失败了，可能是网络原因。

**Comment by Bianzzn** [comment]
大佬 9月3号G站加载不出来了 是什么原因

**Comment by Kkkiddo7** [comment]
拷贝打不开了😭

**Comment by suiyuran** [comment]
> 拷贝打不开了😭

我这边测试没有问题呀

**Comment by Kkkiddo7** [comment]
> > 拷贝打不开了😭
> 
> 我这边测试没有问题呀

我开梯子ok了，但搜索功能不行

**Comment by suiyuran** [comment]
> > > 拷贝打不开了😭
> > 
> > 
> > 我这边测试没有问题呀
> 
> 我开梯子ok了，但搜索功能不行

卸载重装就好了，昨天修复了

**Comment by Kkkiddo7** [comment]
> > > > 拷贝打不开了😭
> > > 
> > > 
> > > 我这边测试没有问题呀
> > 
> > 
> > 我开梯子ok了，但搜索功能不行
> 
> 卸载重装就好了，昨天修复了

可以了！感谢

**Comment by zhaianan** [comment]
大佬noyacg可以加入登录配置吗
