### ISSUE TITLE
大佬可以添加一个包子漫画国内站吗

### ISSUE THREAD

**Issue by whlwmh** [suiyuran/aidoku-zh-sources#51]
G站漫画不行了，https://baozimh.org/

**Comment by suiyuran** [comment]
已添加，以前的包子漫画改名为包子漫画1，新增的为包子漫画2。

**Comment by whlwmh** [comment]
谢谢大佬

**Comment by whlwmh** [comment]
没有找到新的包子漫画

**Comment by whlwmh** [comment]
![FA83849D-1C73-4244-B382-0928C4EF4454](https://github.com/suiyuran/aidoku-zh-sources/assets/167074307/b43231cc-443d-460a-a9f5-ccf727d87f32)

**Comment by suiyuran** [comment]
缓存问题，你可以考虑将图源链接移除后重新添加。
