### ISSUE TITLE
G站漫画章节不能显示了

### ISSUE THREAD

**Issue by MckinleyVan** [suiyuran/aidoku-zh-sources#52]
网站可能是改成
https://godamh.com

**Comment by MckinleyVan** [comment]
原来的https://godamanga.com/会跳转到上面那个新的地址

**Comment by suiyuran** [comment]
新网站漫画章节也无法观看。已添加包子漫画2，和G站漫画内容是一致的。

**Comment by zhaianan** [comment]
目前G站网页可以看，app加载不出章节

**Comment by suiyuran** [comment]
> 目前G站网页可以看，app加载不出章节

已修复。

**Comment by lwluo123** [comment]
好像又不行了，g站和包子2都没有章节

**Comment by suiyuran** [comment]
> 好像又不行了，g站和包子2都没有章节

已修复。

**Comment by lwluo123** [comment]
G站和包子又看不了了，大佬有空修一下，谢谢🙏

**Comment by suiyuran** [comment]
已修复。

**Comment by MckinleyVan** [comment]
佬真的，感谢有你，有没有接受打赏的方式

**Comment by MckinleyVan** [comment]
> 已修复。

佬真的，感谢有你，有没有接受打赏的方式
