### ISSUE TITLE
拷贝源搜索失效

### ISSUE THREAD

**Issue by MareDevi** [suiyuran/aidoku-zh-sources#58]
其余功能正常，搜索无法显示结果

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by YoungWu311** [comment]
官方源的拷贝源是v5版本的搜索功能失效了，此作者的拷贝源是v2版本，我刚试过没有问题

**Comment by MareDevi** [comment]
> 官方源的拷贝源是v5版本的搜索功能失效了，此作者的拷贝源是v2版本，我刚试过没有问题

哦哦，好的
