### ISSUE TITLE
哔咔漫画令牌

### ISSUE THREAD

**Issue by tic0tic0** [suiyuran/aidoku-zh-sources#6]
请问一下大佬，哔咔漫画打开是空白的，输入账号密码之后都没反应。是要填令牌吗？请问该怎么填？谢谢大佬！

**Comment by suiyuran** [comment]
已修复登录问题，卸载哔咔漫画图源之后重新安装，设置好账号和密码就可以了，令牌不需要管，会自动生成。

**Comment by tic0tic0** [comment]
已经解决，感谢
