### ISSUE TITLE
大佬，这个图源现在用不了了吗

### ISSUE THREAD

**Issue by Ka1von** [suiyuran/aidoku-zh-sources#64]
网上只能找到国外图源需要梯，中文图源找不到，这个图源好像失效了，还要新图源吗，所有渠道找的中文图源都是你的链接。

**Comment by Crosell127** [comment]
> 网上只能找到国外图源需要梯，中文图源找不到，这个图源好像失效了，还要新图源吗，所有渠道找的中文图源都是你的链接。

大佬忙
