### ISSUE TITLE
拷贝漫画章节列表显示不全

### ISSUE THREAD

**Issue by Etherrrr** [suiyuran/aidoku-zh-sources#73]
![IMG_0021](https://github.com/user-attachments/assets/159f1062-6c37-4936-b06a-0ea313676c04)
![IMG_0022](https://github.com/user-attachments/assets/1aae83c7-fa62-439a-ba05-ed03037a64b9)

后续更新在“其他汉化版”分支的漫画无法正常显示后续更新

**Comment by suiyuran** [comment]
已修复。
