### ISSUE TITLE
G站漫画和包子漫画2刷新章节后漫画名会显示未找到页面，其它站点没这个问题

### ISSUE THREAD

**Issue by mujinhexi998** [suiyuran/aidoku-zh-sources#79]

**Comment by mujinhexi998** [comment]
还有就是有些漫画app内搜不到但是去网页就能搜到

**Comment by suiyuran** [comment]
刷新章节后漫画名显示未找到页面我已经复现，搜索结果和网页有区别能举个例子吗？

**Comment by mujinhexi998** [comment]
> 刷新章节后漫画名显示未找到页面我已经复现，搜索结果和网页有区别能举个例子吗？

![image](https://github.com/user-attachments/assets/b28a60a0-d306-44f5-9044-41eda77b666d)![image](https://github.com/user-attachments/assets/8a90b47a-bf70-403f-bbd7-69a40eb41f4f)

**Comment by suiyuran** [comment]
已修复。
