### ISSUE TITLE
单行本和普通章节分类问题

### ISSUE THREAD

**Issue by SebastianZzzz** [suiyuran/aidoku-zh-sources#80]
如图所示，有很多漫画源里的漫画把普通章节、单行本甚至全彩版放在不同分类标签下![image](https://github.com/user-attachments/assets/b5319bd1-0a14-438d-b499-5586816fc385)
但是当Aidoku从源中获取章节信息后，所有不同类别的章节都被放在一起了![image](https://github.com/user-attachments/assets/d08d3f18-8276-49e3-9a4f-193cefb5ffa4)
这是否可以通过更新源解决？或者是Aidoku的问题？感谢

**Comment by suiyuran** [comment]
从你截图中的章节列表来看，我判断你这个源是从 aidoku-community-sources 安装的

**Comment by suiyuran** [comment]
目前 Aidoku 的章节列表只有卷和章，没有分类，所以都是放在一起i的

**Comment by SebastianZzzz** [comment]
> 从你截图中的章节列表来看，我判断你这个源是从 aidoku-community-sources 安装的

我测试了一下，确实是community sources的。不过如果用大佬您的源的话，似乎又不加载全彩版单行本了😂

**Comment by suiyuran** [comment]
哪本漫画呢

**Comment by SebastianZzzz** [comment]
> 哪本漫画呢

拷贝漫画 电锯人![image](https://github.com/user-attachments/assets/1d32863b-34fd-496f-9f41-9848bdac924a)

**Comment by SebastianZzzz** [comment]
> 哪本漫画呢

同时，可以麻烦您添加一下更新时间吗？相比之下，community source少了章节分类方式会额外显示更新时间

**Comment by suiyuran** [comment]
修好了，更新时间也加上了。

**Comment by SebastianZzzz** [comment]
> 修好了，更新时间也加上了。

大佬效率太高了，非常感谢
