### ISSUE TITLE
Nhentai图片加载不到

### ISSUE THREAD

**Issue by zhuangssh** [suiyuran/aidoku-zh-sources#82]
![IMG_4774](https://github.com/user-attachments/assets/f61940c8-6283-429e-9b8a-bbdbe3e907c2)
![IMG_4773](https://github.com/user-attachments/assets/97a2bbfd-1245-4293-8e5d-296585880fb0)

**Comment by suiyuran** [comment]
去这儿提，https://github.com/Skittyblock/aidoku-community-sources/issues
