### ISSUE TITLE
漫小肆作者資訊獲取錯誤且無法正常顯示連載狀態

### ISSUE THREAD

**Issue by NeKoOuO** [suiyuran/aidoku-zh-sources#91]
![image](https://github.com/user-attachments/assets/c737f0d6-b7de-4aea-b01c-32f0d4350a20)

**Comment by NeKoOuO** [comment]
正常的
![image](https://github.com/user-attachments/assets/28917cfb-ed8a-426d-9cfc-e8471335091f)

**Comment by suiyuran** [comment]
已修复。
