### ISSUE TITLE
拷贝漫画加载不出来

### ISSUE THREAD

**Issue by spirytuslove** [suiyuran/aidoku-zh-sources#92]
拷贝漫画很多漫画被隐藏了 隐藏的漫画加载不出来

**Comment by NeKoOuO** [comment]
那是源的問題 跟這裡沒關係

**Comment by spirytuslove** [comment]
确实是网站问题 但Tachiyomi里面的这个插件是可以正常看的https://github.com/stevenyomi/copymanga

**Comment by suiyuran** [comment]
具体是哪些漫画呢？举个例子。

**Comment by suiyuran** [comment]
我这边测试都是可以的，你确定源是从这里安装的，而不是 [aidoku-community-sources](https://github.com/Skittyblock/aidoku-community-sources) ?

**Comment by spirytuslove** [comment]
> 我这边测试都是可以的，你确定源是从这里安装的，而不是 [aidoku-community-sources](https://github.com/Skittyblock/aidoku-community-sources) ?

是的 我又重新把所有源去掉重新添加这个 然后把拷贝卸载重新安装也还是这样 就最近拷贝开始隐藏热门漫画才出现这情况的 之前完全没有问题  现在是我上面说的那些热门的漫画点进去加载不了 其他漫画可以正常点进去看的

**Comment by suiyuran** [comment]
源的版本号呢

**Comment by suiyuran** [comment]
现在是 [aidoku-community-sources](https://github.com/Skittyblock/aidoku-community-sources) 和我这边都有拷贝漫画的源，并且 id 都是一样的，但是他那边的版本号要高一些，如果同时添加了两个源的话，安装拷贝漫画就会从 [aidoku-community-sources](https://github.com/Skittyblock/aidoku-community-sources) 安装

**Comment by spirytuslove** [comment]
他那边的还是不行 你这边的是可以的 可能我之前因为源添加了安装的还是那边的 总之感谢
