### ISSUE TITLE
漫小肆無法加載圖源

### ISSUE THREAD

**Issue by NeKoOuO** [suiyuran/aidoku-zh-sources#94]
![image](https://github.com/user-attachments/assets/21845b2d-f366-41ad-ad07-de3ec721ebe0)

**Comment by NeKoOuO** [comment]
有些章節可以有些章節又不行 有點奇怪
測試源 https://www.mxs13.cc/book/1000

https://github.com/user-attachments/assets/1210bc7b-7493-409f-822e-136dc8513cb1

**Comment by suiyuran** [comment]
已修复。
